name: "Betriebsstellen"
description: "A simple search for RIL100-Codes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  csv: ^5.0.0
  dynamic_color: ^1.4.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_svg: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/stations.csv
    - assets/images/placeholder.svg
    - assets/icon.png